# Generated by Django 4.0.4 on 2022-04-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtAPIs', '0005_alter_prime_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factor',
            unique_together={('function', 'query')},
        ),
        migrations.AlterUniqueTogether(
            name='prime',
            unique_together={('function', 'query')},
        ),
    ]
