# Generated by Django 4.0.4 on 2022-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtAPIs', '0008_alter_factor_result_alter_primefactormodel_result_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arithseriesmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='geoseriesmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='arithseriesmodel',
            name='cd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arithseriesmodel',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arithseriesmodel',
            name='terms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoseriesmodel',
            name='cr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoseriesmodel',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoseriesmodel',
            name='terms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='arithseriesmodel',
            unique_together={('function', 'start', 'terms', 'cd')},
        ),
        migrations.AlterUniqueTogether(
            name='geoseriesmodel',
            unique_together={('function', 'start', 'terms', 'cr')},
        ),
        migrations.RemoveField(
            model_name='arithseriesmodel',
            name='query',
        ),
        migrations.RemoveField(
            model_name='geoseriesmodel',
            name='query',
        ),
    ]
