# Generated by Django 4.0.4 on 2022-04-18 07:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExtAPIs', '0016_alter_binarytointmodel_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('function', models.CharField(max_length=256)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('start', models.FloatField(default=0)),
                ('terms', models.IntegerField(default=0)),
                ('cr', models.IntegerField(default=0)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=8191)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_geo_series_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('function', 'start', 'terms', 'cr')},
            },
        ),
        migrations.DeleteModel(
            name='RandomBinary',
        ),
    ]
