# Generated by Django 4.0.4 on 2022-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtAPIs', '0017_geoseriesmodel_delete_randombinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoseriesmodel',
            name='cr',
            field=models.FloatField(default=0),
        ),
    ]
