# Generated by Django 4.0.4 on 2022-04-18 11:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExtAPIs', '0018_alter_geoseriesmodel_cr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectilePath2DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('function', models.CharField(max_length=256)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('launch_angle', models.FloatField(default=0)),
                ('launch_height', models.FloatField(default=0)),
                ('launch_velocity', models.FloatField(default=0)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=8191)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_projectile_2d_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('function', 'launch_angle', 'launch_height', 'launch_velocity')},
            },
        ),
    ]
