# Generated by Django 4.0.4 on 2022-04-14 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExtAPIs', '0002_rename_inttobinary_inttobinarymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinaryToInt',
            new_name='BinaryToIntModel',
        ),
    ]
