# Generated by Django 4.0.4 on 2022-04-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtAPIs', '0014_alter_geoseriesmodel_cr_alter_geoseriesmodel_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoSeriesModel',
        ),
    ]
